# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RecordTechnology' do

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.0'
pod 'OpenUDID', '~>1.0.0'
pod 'MagicalRecord', '~> 2.2'
pod 'Reachability', '~>3.2'
pod 'MFSideMenu', '~> 0.5.5'
pod 'SDWebImage', '~> 3.7.2'
pod 'Masonry', '~> 0.6.1'
pod 'MJRefresh', '~> 2.0.4'
pod 'CocoaLumberjack', '~>2.0.1'
pod 'XTSafeCollection', '~> 1.0.3'

end

target 'RecordTechnologyTests' do

end

