# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RecordTechnology' do

platform :ios, '8.0'
use_frameworks!

#pod 'AFNetworking', '~> 3.1.0'
#pod 'OpenUDID', '~>1.0.0'
#pod 'MagicalRecord', '~> 2.3.2'
#pod 'Reachability', '~>3.2'
#pod 'MFSideMenu', '~> 0.5.5'
#pod 'SDWebImage', '~> 4.1.0'
#pod 'FLAnimatedImage', '~> 1.0.12'
pod 'Masonry', '~> 1.0.2'
#pod 'MJRefresh', '~> 3.1.12'
#pod 'CocoaLumberjack', '~>3.2.1'
#pod 'XTSafeCollection', '~> 1.0.5'
#pod 'pop', '~> 1.0.10'
#pod 'FMDB', '~>2.7.2'
#pod 'JSPatch', '~>1.1.3'
#pod 'Mantle', '~> 2.1.0'
#pod 'ConvertDateAndStringEachOther'
#pod 'AMapLocation', '~>2.4.0'
#pod 'AMap3DMap', '~>5.3.0'
#pod 'AMapSearch', '~>5.3.0'
#pod 'BabyBluetooth', '~> 0.7.0'
#pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager', '= 4.0.13'
#pod 'YYKit', '~> 1.0.9'
pod 'SAMKeychain', '= 1.5.3'

end

target 'RecordTechnologyTests' do

end

